### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by joshacross** [joshacross/devtrax#3]
Displays Name, Email, Username
Has an empty description box to add info/about
Camera Access to take a picture of other QR code > Leads to a separate page to take a picture of QR code or secure one time code *** 
[[Do not look up user by username for privacy, can look up one time codes that are generated by QR codes its just selecting the right widget/API option]]
Generate Contract > Generates QR Code Page
Verification section to upload docs (add placeholders for now)
View History > leads to the history page

**Comment by okni-c** [comment]
Just pushed the profile page rough draft. Still need to add features.
